name: Tebex
version: '${version}'
main: io.tebex.plugin.TebexPlugin
api-version: 1.13
folia-supported: true
softdepend:
  - BuycraftX
commands:
  tebex:
    description: The main command
    aliases:
      - buycraft